### ISSUE TITLE
cromjob lässt sich nicht ausführen

### ISSUE THREAD

**Issue by DHBW-AWZ-Admin** [fluxapps/LearningObjectiveSuggestions#2]
beim Ausfürhen des Cronjobs , kommt ein Fehler:
Exception: Typed property SRAG\ILIAS\Plugins\LearningObjectiveSuggestions\Score\LearningObjectiveScore::$created_at must not be accessed before initialization / #0 /srv/www/htdocs/ilias8/Customizing/global/plugins/Services/Cron/CronHook/LearningObjectiveSuggestions/src/Cron/CalculateScoresAndSuggestionsCronJob.php(108): SRAG\ILIAS\Plugins\LearningObjectiveSugge

**Comment by mstuder** [comment]
Fehler wurde behoben für die weitere Prüfung bräuchte ich von dir das von euch verwendete CascadingSelect: https://github.com/fluxapps/UserDefaults/issues/18#issuecomment-1872499931
